"""
pipeline/paper/conventions.py - Canonical sign conventions.

THE CANONICAL CONVENTION
------------------------
    illusion_strength > 0  ->  INCONGRUENT (illusion opposes the true difference)
    illusion_strength < 0  ->  CONGRUENT   (illusion supports it)
    true_diff        > 0  ->  the positive response option is correct

Everything downstream assumes this. Data from either species is mapped onto it
here, so no other module needs to reason about sign.

WHAT THE STRENGTH SIGN ENCODES
------------------------------
In this stimulus set (inherited from the Illusion Game) the sign of
illusion_strength encodes CONGRUENCY RELATIVE TO THE TRUE DIFFERENCE, not a
fixed spatial direction. In the human data congruency is determined by
sign(illusion_strength) alone and is independent of sign(true_diff):
P(Incongruent | strength > 0) is exactly 0 or 1 for every illusion.

A group of trials sharing one signed strength therefore contains trials in
which the illusion points in opposite spatial directions, and its pooled
response function is not monotonic in delta. Recovering a monotonic
arrangement requires slicing on the illusion's spatial direction, which
metrics.add_illusion_direction does.

PER-ILLUSION FLIPS
------------------
Both flips below were determined from the response data and the rendered
stimuli rather than from library changelogs.

FLIP_VLM = {"Delboeuf"}
    Our Delboeuf stimuli carry the opposite sign to the other six. Accuracy is
    higher at positive than at negative strength (0.992 vs 0.812 at the
    extremes), the reverse of every other illusion and of the human data
    (0.571 vs 0.926).

    CAUSE, AND WHY THIS FLIP DOES NOT MAKE THE TWO DATASETS COMPARABLE.
    Pyllusion changed the Delboeuf generator in commit 4ee0c33c
    (2022-09-05, issue #17 "Fixed Delboeuf"):

        - outer_size = inner_size + (0.2 * size_min)
        + outer_size = inner_size

    Before that commit both target circles carried a visible outline and one
    was then enlarged; after it the unenlarged side's outline coincides with
    its target and is invisible, so only one circle is ringed and at zero
    strength neither is. The human Illusion Game data were collected
    2022-08-05 to 2022-08-27 on Pyllusion 1.2, before the commit; our stimuli
    were generated after it. Measured on our PNGs, exactly one side is ringed
    at every non-zero strength and the ring/target ratio runs 1.14 to 1.78.

    The flip aligns the congruency label with our own stimuli, but it does not
    make our Delboeuf the same stimulus as the human one. Delboeuf is
    therefore not usable for a human-model contrast without regenerating one
    side under the other's version.

GENERATOR CHANGED AFTER THE HUMAN DATA
--------------------------------------
Of the seven illusions we test, only two had Pyllusion commits after human
collection ended on 2022-08-27, so only these two are generated by different
code on the two sides of the comparison:

    Delboeuf    4ee0c33c 2022-09-05, e47a0be6 2022-09-06, 83a5eaaa 2022-09-16
                The first changes the stimulus materially; see FLIP_VLM.
    Ebbinghaus  f472ebac 2022-10-13 mirrors the distractor layout between
                sides; fca5a5c6 2024-02-29 adds a colour argument.

MullerLyer, Ponzo, VerticalHorizontal, Contrast and RodFrame are untouched
since before that date, so their stimuli match the human ones.

Pyllusion's documented ILLUSION-STRENGTH SIGN reversals affect a different
set: Zollner, Poggendorff, White and Contrast in 1.1.0, and Zollner again
afterwards. Of those we test only Contrast, and its generator has not changed
since the human data, so no flip applies. A later entry also inverts the
RodFrame `difference` effect, but that commit predates human collection and
RodFrame has not changed since.

FLIP_HUMAN = {}
    The published human strengths are already canonical for all ten illusions:
    accuracy is high at negative strength and low at positive for each.

    config.py carries a note, taken from Pyllusion's changelog, that the human
    comparison needs an x-axis flip for Contrast, White, Zollner and
    Poggendorff. That does not hold for the observed data: Contrast follows the
    same accuracy ordering as the others in both species, so applying the flip
    would invert its congruency axis. Of the four, only Contrast is in our
    illusion set.
"""

from __future__ import annotations

import pandas as pd

# Illusions whose illusion_strength sign must be flipped to reach the
# canonical convention. See the module docstring for the evidence.
FLIP_VLM = {"Delboeuf"}
FLIP_HUMAN: set[str] = set()

# Every illusion in the dataset, in the order the analysis tables use. All of
# these are built, fitted and written to results/_paper/; FIGURE_ILLUSIONS
# controls which of them the main figures draw.
ILLUSION_ORDER = [
    "MullerLyer",
    "VerticalHorizontal",
    "Ponzo",
    "Ebbinghaus",
    "Delboeuf",
    "Contrast",
    "RodFrame",
]

# The subset the main figures show. Only Rod-Frame is held out, and it stays in
# the dataset and every analysis table.
#
# The criterion is whether a psychometric function describes the model's
# responses at all, measured per direction slice on the shared grid as the
# number of slices whose response curve doubles back (drawdown > 0.35):
#
#     Delboeuf 0/14   Muller-Lyer 0/14   Ponzo 1/14
#     Ebbinghaus 2/14  Vertical-Horizontal 2/14   Contrast 4/14
#     Rod-Frame 12/14
#
# Rod-Frame is the only illusion in a different league; the rest form a
# continuum and excluding any of them would be an arbitrary cut. Humans are
# 0/14 with r-squared above 0.98 on all seven.
FIGURES_EXCLUDED = {"RodFrame"}
FIGURE_ILLUSIONS = [i for i in ILLUSION_ORDER if i not in FIGURES_EXCLUDED]


# Where an illusion's stimulus images live, when that is not a directory of the
# same name. Delboeuf must be drawn from the Pyllusion 1.2-equivalent set: the
# installed Pyllusion postdates commit 4ee0c33c, which changed the outer-circle
# base size, so the plain `Delboeuf` directory does not hold the images the
# human participants saw. See pipeline/delboeuf_v12.py.
STIMULUS_SOURCE = {"Delboeuf": "DelboeufV12"}


def stimulus_dir_name(illusion: str) -> str:
    """The directory under stimuli/ holding this illusion's images."""
    return STIMULUS_SOURCE.get(illusion, illusion)


# Display names for axis labels and captions.
DISPLAY_NAMES = {
    "MullerLyer": "Müller-Lyer",
    "VerticalHorizontal": "Vertical-Horizontal",
    "Ponzo": "Ponzo",
    "Ebbinghaus": "Ebbinghaus",
    "Delboeuf": "Delboeuf",
    "Contrast": "Contrast",
    "RodFrame": "Rod-Frame",
}


def apply_canonical_signs(
    df: pd.DataFrame,
    species: str,
    illusion_col: str = "illusion",
    strength_col: str = "illusion_strength",
) -> pd.DataFrame:
    """
    Flip illusion_strength where needed so `df` follows the canonical convention.

    Args:
        df:           Trial-level or cell-level data.
        species:      "vlm" or "human".
        illusion_col: Column holding our illusion name.
        strength_col: Column holding the signed illusion strength.

    Returns:
        A copy with the sign corrected and a `strength_sign_flipped` column
        recording which rows were changed, so figures can disclose it.

    Raises:
        ValueError: on an unknown species.
    """
    if species not in ("vlm", "human"):
        raise ValueError(f"species must be 'vlm' or 'human', got {species!r}")

    flips = FLIP_VLM if species == "vlm" else FLIP_HUMAN
    out = df.copy()
    mask = out[illusion_col].isin(flips)
    out.loc[mask, strength_col] = -out.loc[mask, strength_col]
    out["strength_sign_flipped"] = mask
    return out


def congruency(strength: float) -> str:
    """Label a canonical signed strength."""
    if strength > 0:
        return "incongruent"
    if strength < 0:
        return "congruent"
    return "baseline"
